# Generated by Django 4.0.4 on 2022-06-02 06:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(primary_key=True, serialize=False, unique_with=('name', 'type_of_service')),
        ),
    ]
