# Generated by Django 4.0.4 on 2022-06-02 07:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0002_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', primary_key=True, serialize=False),
        ),
    ]
