# Generated by Django 4.0.4 on 2022-06-02 07:11

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_service', '0004_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
